name: omegaui
description: "A passionate and self-made developer, known for unleashing the full potential of technology in its most exceptional form."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  animated_background: ^2.0.0
  gap: ^3.0.1
  flutter_audio_waveforms: ^1.2.1+8
  just_audio: ^0.9.36
  video_player: ^2.8.2
  url_launcher: ^6.2.3
  http: ^1.2.0
  intl: ^0.19.0
  url_launcher_web: ^2.2.3
  video_player_web: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/illustrations/
    - assets/music/
    - assets/images/
  fonts:
    - family: Sen
      fonts:
        - asset: fonts/Sen/Sen-Regular.ttf
          weight: 400
        - asset: fonts/Sen/Sen-Medium.ttf
          weight: 500
        - asset: fonts/Sen/Sen-Bold.ttf
          weight: 700
    - family: Satoshi
      fonts:
        - asset: fonts/Satoshi/Satoshi-Regular.otf
          weight: 400
        - asset: fonts/Satoshi/Satoshi-Medium.otf
          weight: 500
        - asset: fonts/Satoshi/Satoshi-Bold.otf
          weight: 700

